[[main]]
  identifier = "agenda"
  name = "Agenda"
  url = "agenda"
  weight = 20

[[main]]
  identifier = "assignment"
  name = "Assignments"
  url = "a"
  weight = 30

[[main]]
  identifier = "guide"
  name = "Guides"
  url = "guide"
  weight = 40

[[main]]
  identifier = "syllabus"
  name = "Syllabus"
  url = "syllabus"
  weight = 10
