#[[main]]
#  identifier = "module"
#  name = "Modules"
#  url = "module"
#  weight = 1
#
[[main]]
  identifier = "assignment"
  name = "Assignments"
  url = "a"
  weight = 30

[[main]]
  identifier = "guide"
  name = "Guides"
  url = "guide"
  weight = 40

[[main]]
  identifier = "syllabus"
  name = "Syllabus"
  url = "syllabus"
  weight = 10
