name: Publish Site

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
        with:
          submodules: true
      - name: Publish Site
        uses: jdmar3/comp426@main
        with:
          githubToken: ${{ secrets.PERSONAL_TOKEN }}
          cname: comp426.johndmart.in # Or anything else
          hugoVersion: extended_0.80.0
