name: Publish Site

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Publish Site
        uses: jdmar3/comp426@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          cname: comp426.johndmart.in # Or anything else
          hugoVersion: extended_0.80.0
